# Generated by Django 3.1.4 on 2021-03-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sockets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socket',
            old_name='group_id',
            new_name='room_id',
        ),
        migrations.RemoveField(
            model_name='socket',
            name='group_type',
        ),
        migrations.AddField(
            model_name='socket',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
