# Generated by Django 3.1.4 on 2021-03-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sockets', '0002_auto_20210315_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socket',
            name='connected_at',
        ),
    ]
