# Generated by Django 3.1.4 on 2021-03-15 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_sockets', '0003_remove_socket_connected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socket',
            name='id',
        ),
        migrations.AddField(
            model_name='socket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
