# Generated by Django 3.1.4 on 2021-01-25 04:30

import app_users.enums
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0005_auto_20210120_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='required_docs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[('Пасспорт', app_users.enums.DocumentType['PASSPORT']), ('ИНН', app_users.enums.DocumentType['INN']), ('СНИЛС', app_users.enums.DocumentType['SNILS']), ('Медкнижка', app_users.enums.DocumentType['MEDICAL_BOOK']), ('Водительское удостоверение', app_users.enums.DocumentType['DRIVER_LICENCE'])]), blank=True, null=True, size=None),
        ),
    ]
