# Generated by Django 3.1.4 on 2021-01-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0006_auto_20210111_1352'),
        ('app_market', '0007_auto_20210125_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_geo.city'),
        ),
    ]
