# Generated by Django 3.1.4 on 2021-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0008_shop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, choices=[(3, 'Ежедневно'), (2, 'Еженедельно'), (1, 'Ежемесячно')], null=True, verbose_name='Интервал выполнения'),
        ),
    ]
