# Generated by Django 3.1.4 on 2021-01-29 08:18

import app_users.enums
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0009_auto_20210128_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='required_docs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(app_users.enums.DocumentType['PASSPORT'], 'Паспорт'), (app_users.enums.DocumentType['INN'], 'ИНН'), (app_users.enums.DocumentType['SNILS'], 'СНИЛС'), (app_users.enums.DocumentType['MEDICAL_BOOK'], 'Медкнижка'), (app_users.enums.DocumentType['DRIVER_LICENCE'], 'Водительское удостоверение')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='required_docs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(app_users.enums.DocumentType['PASSPORT'], 'Паспорт'), (app_users.enums.DocumentType['INN'], 'ИНН'), (app_users.enums.DocumentType['SNILS'], 'СНИЛС'), (app_users.enums.DocumentType['MEDICAL_BOOK'], 'Медкнижка'), (app_users.enums.DocumentType['DRIVER_LICENCE'], 'Водительское удостоверение')]), blank=True, null=True, size=None, verbose_name='Документы'),
        ),
    ]
