# Generated by Django 3.1.4 on 2021-02-08 12:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0013_auto_20210208_1337'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vacancy',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='app_market__vacancies__title', opclasses=('gin_trgm_ops',)),
        ),
    ]
