# Generated by Django 3.1.4 on 2021-02-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0014_auto_20210208_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='generated_active_dates',
        ),
    ]
