# Generated by Django 3.1.4 on 2021-02-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0016_auto_20210216_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='rates_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок торговой сети'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг торговой сети'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rates_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг магазина'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='rates_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
