# Generated by Django 3.1.4 on 2021-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0017_auto_20210219_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employees_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число работников сейчас'),
        ),
    ]
