# Generated by Django 3.1.4 on 2021-03-15 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0018_auto_20210224_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='available_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
