# Generated by Django 3.1.4 on 2021-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0019_vacancy_available_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='places_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
