# Generated by Django 3.1.4 on 2021-03-17 22:20

import app_market.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0020_vacancy_places_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershift',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'INITIAL'), (1, 'STARTED'), (2, 'COMPLETED'), (3, 'REJECTED')], default=app_market.enums.ShiftStatus['INITIAL']),
        ),
        migrations.CreateModel(
            name='ShiftAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(0, 'INITIAL'), (1, 'CONFIRMED'), (3, 'REJECTED')], default=app_market.enums.ShiftAppealStatus['INITIAL'])),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='app_market.shift')),
            ],
            options={
                'verbose_name': 'Отклик на рабочую смену',
                'verbose_name_plural': 'Отклики на рабочие смены',
                'db_table': 'app_market__shifts_appeals',
            },
        ),
    ]
