# Generated by Django 3.1.4 on 2021-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0021_auto_20210317_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershift',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='usershift',
            name='qr_data',
            field=models.JSONField(default=dict),
        ),
    ]
