# Generated by Django 3.1.4 on 2021-03-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0022_auto_20210319_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='places_count',
        ),
    ]
