# Generated by Django 3.1.4 on 2021-04-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0023_auto_20210324_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='shift_active_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
