# Generated by Django 3.1.4 on 2021-04-22 08:48

import app_market.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0024_shiftappeal_shift_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='cancel_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'CUSTOM'), (1, 'MISTAKE'), (2, 'ACCIDENT')], null=True, verbose_name='Причина отмены самозанятым'),
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='reason_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст причины отменыF'),
        ),
        migrations.AlterField(
            model_name='shiftappeal',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'INITIAL'), (1, 'CONFIRMED'), (2, 'CANCELED'), (3, 'REJECTED')], default=app_market.enums.ShiftAppealStatus['INITIAL']),
        ),
    ]
