# Generated by Django 3.1.4 on 2021-04-26 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0011_auto_20210324_1010'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0026_auto_20210423_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_media.mediamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.vacancy')),
            ],
            options={
                'verbose_name': 'Документ вакансии для пользователя',
                'verbose_name_plural': 'Документы вакансий для пользователей',
                'db_table': 'app_market__user_vacancy_document',
            },
        ),
        migrations.CreateModel(
            name='GlobalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_media.mediamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ сервиса для пользователя',
                'verbose_name_plural': 'Документы сервиса для пользователей',
                'db_table': 'app_market__user_global_document',
            },
        ),
        migrations.CreateModel(
            name='DistributorDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.distributor')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_media.mediamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ торговой сети для пользователя',
                'verbose_name_plural': 'Документы торговых сетей для пользователей',
                'db_table': 'app_market__user_distributor_document',
            },
        ),
    ]
