# Generated by Django 3.1.4 on 2021-04-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0027_distributordocument_globaldocument_vacancydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания смены'),
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала смены'),
        ),
        migrations.AlterField(
            model_name='shiftappeal',
            name='reason_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст причины отмены'),
        ),
    ]
