# Generated by Django 3.1.4 on 2021-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0029_auto_20210511_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время закрытия магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время открытия магазина'),
        ),
    ]
