# Generated by Django 3.1.4 on 2021-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0030_auto_20210511_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='manager_cancel_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'CUSTOM'), (1, 'MISTAKE'), (2, 'ACCIDENT'), (3, 'NO_PASSPORT'), (4, 'WRONG_PASSPORT'), (5, 'NO_INN'), (6, 'NO_SNILS'), (7, 'NO_MEDICAL_BOOK'), (8, 'NO_DRIVER_LICENCE')], null=True, verbose_name='Причина отмены менеджером'),
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='manager_reason_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст причины'),
        ),
    ]
