# Generated by Django 3.1.4 on 2021-06-01 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0031_auto_20210527_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='job_status',
            field=models.PositiveIntegerField(blank=True, choices=[(2, 'JOB_SOON'), (3, 'JOB_IN_PROCESS'), (4, 'WAITING_FOR_COMPLETION'), (5, 'COMPLETED')], default=None, null=True, verbose_name='Статус работы'),
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время окончания смены'),
        ),
        migrations.AlterField(
            model_name='shiftappeal',
            name='applier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL),
        ),
    ]
