# Generated by Django 3.1.4 on 2021-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0032_auto_20210601_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='qr_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
