# Generated by Django 3.1.4 on 2021-06-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0034_auto_20210603_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftappeal',
            old_name='qr_scan_time',
            new_name='security_qr_scan_time',
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='manager_qr_scan_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время сканирования QR кода менеджером'),
        ),
    ]
