# Generated by Django 3.1.4 on 2021-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0036_auto_20210603_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='fire_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'CUSTOM')], null=True, verbose_name='Причина увольнения менеджером'),
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='fire_reason_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст причины увольнения менеджером'),
        ),
    ]
