# Generated by Django 3.1.4 on 2021-06-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0037_auto_20210603_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.profession', verbose_name='Профессия'),
        ),
    ]
