# Generated by Django 3.1.4 on 2021-06-09 06:17

import app_market.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0038_vacancy_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftappeal',
            name='fire_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'CUSTOM'), (1, 'INCOMPETENT'), (2, 'DRUNK')], null=True, verbose_name='Причина увольнения менеджером'),
        ),
        migrations.AlterField(
            model_name='usershift',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'INITIAL'), (1, 'STARTED'), (2, 'CANCELED'), (3, 'REJECTED'), (4, 'COMPLETED')], default=app_market.enums.ShiftStatus['INITIAL']),
        ),
    ]
