# Generated by Django 3.1.4 on 2021-06-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0040_auto_20210609_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftappeal',
            old_name='manager_reason_text',
            new_name='cancel_reason_text',
        ),
        migrations.RenameField(
            model_name='shiftappeal',
            old_name='fire_reason',
            new_name='manager_fire_reason',
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='manager_refuse_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'WRONG_DOCUMENTS'), (2, 'UNABLE_TO_WORK')], null=True, verbose_name='Причина отклонения отклика'),
        ),
        migrations.AddField(
            model_name='shiftappeal',
            name='refuse_reason_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст причины отклонения отклика'),
        ),
        migrations.AlterField(
            model_name='shiftappeal',
            name='manager_cancel_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'CUSTOM'), (1, 'MISTAKE'), (2, 'ACCIDENT'), (3, 'NO_PASSPORT'), (4, 'WRONG_PASSPORT'), (5, 'NO_INN'), (6, 'NO_SNILS'), (7, 'NO_MEDICAL_BOOK'), (8, 'NO_DRIVER_LICENCE')], null=True, verbose_name='Причина отмены менеджером'),
        ),
    ]
