# Generated by Django 3.1.4 on 2021-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0042_auto_20210610_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftappeal',
            name='fire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время увольнения'),
        ),
        migrations.AlterField(
            model_name='shiftappeal',
            name='job_status',
            field=models.PositiveIntegerField(blank=True, choices=[(2, 'JOB_SOON'), (3, 'JOB_IN_PROCESS'), (4, 'WAITING_FOR_COMPLETION'), (5, 'COMPLETED'), (6, 'WAITING_FOR_FIRING'), (7, 'FIRED')], default=None, null=True, verbose_name='Статус работы'),
        ),
    ]
