# Generated by Django 3.1.4 on 2021-07-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0048_achievementprogress_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementprogress',
            name='actions_count',
        ),
        migrations.AddField(
            model_name='achievementprogress',
            name='achieved_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Получено раз'),
        ),
        migrations.AlterField(
            model_name='achievementprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения прогресса по достижению'),
        ),
        migrations.AlterField(
            model_name='achievementprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала накопления прогресса по достижению'),
        ),
    ]
