# Generated by Django 3.1.4 on 2021-07-05 07:30

import app_market.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0049_auto_20210702_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_content_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_content_type_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_content_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_content_type_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.partner'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'TEST'), (1, 'TRANSFER'), (2, 'DEPOSIT'), (3, 'WITHDRAWAL'), (4, 'RETURN'), (5, 'PURCHASE')], default=app_market.enums.TransactionType['TRANSFER'], verbose_name='Тип транзакции'),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Купон ползователя',
                'verbose_name_plural': 'Купоны пользователей',
                'db_table': 'app_market__coupon_user',
            },
        ),
    ]
