# Generated by Django 3.1.4 on 2021-07-05 11:17

import app_market.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0052_auto_20210705_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'TEST'), (1, 'TRANSFER'), (2, 'DEPOSIT'), (3, 'WITHDRAWAL'), (4, 'PURCHASE'), (5, 'RETURN')], default=app_market.enums.TransactionType['TRANSFER'], verbose_name='Тип транзакции'),
        ),
    ]
