# Generated by Django 3.1.4 on 2021-07-05 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0013_auto_20210630_1510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0053_auto_20210705_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_partner_documents', to='app_media.mediamodel')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ Магазина-Партнера для пользователя',
                'verbose_name_plural': 'Документы Магазинов-Партнеров для пользователей',
                'db_table': 'app_market__user_partner_document',
            },
        ),
    ]
