# Generated by Django 3.1.4 on 2021-07-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0054_partnerdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoupon',
            options={'verbose_name': 'Купон пользователя', 'verbose_name_plural': 'Купоны пользователей'},
        ),
    ]
