# Generated by Django 3.1.4 on 2021-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0055_auto_20210705_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_ct_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_ct_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
