# Generated by Django 3.1.4 on 2021-07-08 05:37

import app_market.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0056_auto_20210705_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'PAY'), (2, 'TAXES'), (3, 'INSURANCE'), (4, 'PENALTY'), (5, 'FRIEND_REWARD')], null=True, verbose_name='Вид транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'TEST'), (1, 'TRANSFER'), (2, 'DEPOSIT'), (3, 'WITHDRAWAL'), (4, 'PURCHASE'), (5, 'RETURN'), (6, 'COMMISSION')], default=app_market.enums.TransactionType['TRANSFER'], verbose_name='Тип транзакции'),
        ),
    ]
