# Generated by Django 3.1.4 on 2021-07-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0057_auto_20210708_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employees_count',
        ),
        migrations.AddField(
            model_name='shift',
            name='auto_control_threshold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минут до начала смены для автоконтроля'),
        ),
        migrations.AddField(
            model_name='shift',
            name='min_employee_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальный рейтинг работника для автоконтроля'),
        ),
    ]
