# Generated by Django 3.1.4 on 2021-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0058_auto_20210713_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет'),
        ),
    ]
