# Generated by Django 3.1.4 on 2021-07-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0061_auto_20210713_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.partner')),
            ],
            options={
                'verbose_name': 'Код купона',
                'verbose_name_plural': 'Коды Купонов',
                'db_table': 'app_market__codes',
            },
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.code')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Купон пользователя',
                'verbose_name_plural': 'Купоны пользователей',
                'db_table': 'app_market__code_user',
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
