# Generated by Django 3.1.4 on 2021-07-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0062_auto_20210713_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='app_market.coupon'),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='app_market.code'),
        ),
    ]
