# Generated by Django 3.1.4 on 2021-08-03 07:47

import app_market.enums
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0063_auto_20210713_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAppealInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер полиса')),
                ('insurer', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Страховщик')),
                ('insured_birth_date', models.DateTimeField(blank=True, null=True)),
                ('insured_passport', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_email', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_reg_address', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_address', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=255, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало страхового периода')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание страхового периода')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.PositiveIntegerField(choices=[(0, 'BONUS'), (1, 'USD'), (2, 'EUR'), (3, 'RUB')], default=app_market.enums.Currency['RUB'], verbose_name='Валюта')),
                ('insurance_premium', models.PositiveIntegerField(blank=True, null=True)),
                ('insurance_payment_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Срок оплаты страховой премии')),
                ('insured_description', models.TextField(blank=True, max_length=4096, null=True)),
                ('risks', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=10)),
                ('risks_description', models.TextField(blank=True, max_length=4096, null=True)),
                ('special_conditions', models.TextField(blank=True, max_length=4096, null=True)),
                ('insurer_proxy_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер доверенности представителя страховщика')),
                ('insurer_sign', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись страхователя')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='app_market.shiftappeal')),
            ],
            options={
                'verbose_name': 'Страховка на период рабочей смены',
                'verbose_name_plural': 'Страховки на период рабочих смен',
                'db_table': 'app_market__shift_appeal_insurance',
            },
        ),
    ]
