# Generated by Django 3.1.4 on 2021-08-26 09:17

import app_market.enums
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0067_auto_20210825_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='required_experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(0, 'NO'), (1, 'INVALID'), (2, 'UNDERAGE'), (3, 'MIDDLE'), (4, 'STRONG')], default=app_market.enums.WorkExperience['NO']), blank=True, null=True, size=None, verbose_name='Требуемый опыт'),
        ),
    ]
