# Generated by Django 3.1.4 on 2021-08-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0068_auto_20210826_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Бизнес-регион',
                'verbose_name_plural': 'Бизнес-регионы',
                'db_table': 'app_market__structures',
            },
        ),
        migrations.CreateModel(
            name='DistributorStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.distributor')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.structure')),
            ],
            options={
                'verbose_name': 'Бизнес-регион торговой сети',
                'verbose_name_plural': 'Бизнес-регионы торговых сетей',
                'db_table': 'app_market__distributor_structure',
            },
        ),
    ]
