# Generated by Django 3.1.4 on 2021-09-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0070_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('short_name', models.CharField(blank=True, max_length=512, null=True)),
                ('full_name', models.CharField(blank=True, max_length=512, null=True)),
                ('inn', models.CharField(blank=True, max_length=12, null=True)),
                ('kpp', models.CharField(blank=True, max_length=12, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.distributor')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'app_market__organizations',
            },
        ),
    ]
