version: '3.5'

networks:
  giberno_release:

services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - giberno_release
  db:
    image: postgis/postgis:13-3.0
    restart: always
    networks:
      - giberno_release
    environment:
      POSTGRES_DB: ${RL_POSTGRES_DB}
      POSTGRES_USER: ${RL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RL_POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  daphne:
    image: registry.appcraft.team:5005/giberno/giberno-server
    restart: always
    command: bash -c "python3 manage.py migrate && python3 manage.py seed && python3 manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p ${RL_DAPHNE_PORT} giberno.asgi:application"
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      CELERY_BROKER: redis://redis:6379/0
      MACHINE_HOST: 127.0.0.1
      HOST_IP: ${RL_HOST_IP}
      HOST_PORT: ${RL_DAPHNE_PORT}
      NGINX_PORT: ${RL_NGINX_PORT}
      HOST_DOMAIN: ${RL_HOST_DOMAIN}
      DB_NAME: ${RL_POSTGRES_DB}
      DB_USER: ${RL_POSTGRES_USER}
      DB_PASSWORD: ${RL_POSTGRES_PASSWORD}
      SUPERUSER_PASS: ${RL_SUPERUSER_PASS}
      ENVIRONMENT: ${RL_ENVIRONMENT}
    ports:
      - "127.0.0.1:${RL_DAPHNE_PORT}:${RL_DAPHNE_PORT}"
    networks:
      - giberno_release
    depends_on:
      - db
      - redis
    volumes:
      - ./files:/code/files
  celery:
    image: registry.appcraft.team:5005/giberno/giberno-server
    command: celery -A giberno worker -l info
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      CELERY_BROKER: redis://redis:6379/0
      MACHINE_HOST: 127.0.0.1
      HOST_IP: ${RL_HOST_IP}
      HOST_PORT: ${RL_DAPHNE_PORT}
      NGINX_PORT: ${RL_NGINX_PORT}
      HOST_DOMAIN: ${RL_HOST_DOMAIN}
      DB_NAME: ${RL_POSTGRES_DB}
      DB_USER: ${RL_POSTGRES_USER}
      DB_PASSWORD: ${RL_POSTGRES_PASSWORD}
      SUPERUSER_PASS: ${RL_SUPERUSER_PASS}
      ENVIRONMENT: ${RL_ENVIRONMENT}
    depends_on:
      - db
      - redis
    networks:
      - giberno_release
    volumes:
      - ./files:/code/files
  celery-beat:
    image: registry.appcraft.team:5005/giberno/giberno-server
    command: celery -A giberno beat -l info
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      CELERY_BROKER: redis://redis:6379/0
      MACHINE_HOST: 127.0.0.1
      HOST_IP: ${RL_HOST_IP}
      HOST_PORT: ${RL_DAPHNE_PORT}
      NGINX_PORT: ${RL_NGINX_PORT}
      HOST_DOMAIN: ${RL_HOST_DOMAIN}
      DB_NAME: ${RL_POSTGRES_DB}
      DB_USER: ${RL_POSTGRES_USER}
      DB_PASSWORD: ${RL_POSTGRES_PASSWORD}
      SUPERUSER_PASS: ${RL_SUPERUSER_PASS}
      ENVIRONMENT: ${RL_ENVIRONMENT}
    depends_on:
      - db
      - redis
    networks:
      - giberno_release
    volumes:
      - ./files:/code/files