# Generated by Django 3.2.5 on 2021-07-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NalogRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(verbose_name='Уникальный идентификатор запроса')),
                ('request_xml', models.TextField(verbose_name='Полный XML запроса')),
                ('message_id', models.CharField(max_length=255, verbose_name='MessageID')),
                ('response_xml', models.TextField(blank=True, null=True, verbose_name='Полный XML ответа GetMessage')),
            ],
            options={
                'verbose_name': 'Лог запроса',
                'verbose_name_plural': 'Логи запросов',
                'db_table': 'appcraft_nalog_sdk_request_logs',
            },
        ),
        migrations.CreateModel(
            name='NalogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН пользователя')),
                ('status', models.IntegerField(choices=[(0, 'Пользователь не является самозанятым'), (1, 'Пользователь является самозанятым, но не привязан к партнеру'), (2, 'Пользователь самозанятый и привязан к партнеру'), (3, 'Неизвестный статус, возможна ошибка в данных')], verbose_name='Статус самозанятого')),
            ],
            options={
                'verbose_name': 'Налоговый пользователь',
                'verbose_name_plural': 'Налоговые пользователи',
                'db_table': 'appcraft_nalog_sdk_users',
            },
        ),
    ]
