# Generated by Django 3.2.5 on 2021-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogrequestmodel',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Запрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nalogrequestmodel',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Message ID'),
        ),
    ]
