# Generated by Django 3.2.5 on 2021-07-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0002_auto_20210727_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naloguser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Пользователь не является самозанятым'), (1, 'Пользователь является самозанятым, но не привязан к партнеру'), (2, 'Пользователь самозанятый и привязан к партнеру'), (3, 'Неизвестный статус, возможна ошибка в данных')], default=3, verbose_name='Статус самозанятого'),
        ),
        migrations.CreateModel(
            name='NalogNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_id', models.IntegerField(verbose_name='ID Уведомления в ФНС')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(max_length=255, verbose_name='Статус уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcraft_nalog_sdk.naloguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'appcraft_nalog_notifications',
            },
        ),
    ]
