# Generated by Django 3.2.5 on 2021-07-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0003_auto_20210727_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='NalogBindPartnerRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(max_length=255, verbose_name='ID заявки')),
                ('status', models.CharField(choices=[('COMPLETED', 'Заявка на выдачу прав рассмотрена'), ('FAILED', 'Заявка на выдачу прав отклонена'), ('IN_PROGRESS', 'Заявка на выдачу прав находится на рассмотрении')], default='IN_PROGRESS', max_length=255, verbose_name='Статус заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcraft_nalog_sdk.naloguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на привязку к партнеру',
                'verbose_name_plural': 'Заявки на привязку к партнеру',
                'db_table': 'appcraft_nalog_sdk_bind_partner_requests',
            },
        ),
    ]
