# Generated by Django 3.2.5 on 2021-07-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0005_naloguser_is_tax_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NalogIncomeRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(verbose_name='Уникальный идентификатор операции')),
                ('amount', models.FloatField(verbose_name='Сумма дохода')),
                ('name', models.CharField(max_length=255, verbose_name='Название дохода')),
                ('receipt_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID чека')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на чек')),
                ('operation_time', models.DateTimeField(verbose_name='Дата совершение услуги')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcraft_nalog_sdk.naloguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация дохода',
                'verbose_name_plural': 'Регистрация доходов',
                'db_table': 'appcraft_nalog_sdk_income_requests',
            },
        ),
    ]
