# Generated by Django 3.2.5 on 2021-07-28 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0006_nalogincomerequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogincomerequestmodel',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 8, 55, 55, 440576, tzinfo=utc), verbose_name='Дата совершение услуги'),
            preserve_default=False,
        ),
    ]
