# Generated by Django 3.2.5 on 2021-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0007_nalogincomerequestmodel_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogincomerequestmodel',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
