# Generated by Django 3.2.5 on 2021-07-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0009_auto_20210728_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogrequestmodel',
            name='status',
            field=models.TextField(choices=[('PROCESSING', 'В процессе'), ('COMPLETED', 'Выполнен')], default='PROCESSING', verbose_name='Статус выполнения'),
        ),
        migrations.AddField(
            model_name='nalogrequestmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appcraft_nalog_sdk.naloguser', verbose_name='Пользователь, над которым совершается операция'),
        ),
    ]
