# Generated by Django 3.2.5 on 2021-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0010_auto_20210729_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalogrequestmodel',
            name='name',
            field=models.TextField(choices=[('AuthRequest', 'Auth Request'), ('GetTaxpayerStatusRequest', 'Get Taxpayer Status Request')], verbose_name='Запрос'),
        ),
    ]
