# Generated by Django 3.2.5 on 2021-07-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0011_alter_nalogrequestmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nalogrequestmodel',
            name='uuid',
        ),
    ]
