# Generated by Django 3.2.5 on 2021-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0012_remove_nalogrequestmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogincomerequestmodel',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MessageID'),
        ),
        migrations.AlterField(
            model_name='nalogrequestmodel',
            name='name',
            field=models.TextField(choices=[('AuthRequest', 'Auth Request'), ('GetTaxpayerStatusRequest', 'Get Taxpayer Status Request'), ('GetNotificationsRequest', 'Get Notifications Request'), ('PostBindPartnerWithInnRequest', 'Post Bind Partner With Inn Request'), ('GetBindPartnerStatusRequest', 'Get Bind Partner Status Request'), ('PostIncomeRequestV2', 'Post Income Request V2'), ('PostCancelReceiptRequestV2', 'Post Cancel Receipt Request V2'), ('GetGrantedPermissionsRequest', 'Get Granted Permissions Request'), ('GetCancelIncomeReasonsListRequest', 'Get Cancel Income Reasons List Request'), ('PostPlatformRegistrationRequest', 'Post Platform Registration Request'), ('PostNotificationsAckRequest', 'Post Notifications Ack Request')], verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='nalogrequestmodel',
            name='status',
            field=models.TextField(choices=[('PROCESSING', 'В процессе'), ('COMPLETED', 'Выполнен'), ('NOT_FOUND', 'MessageID истек или не найден')], default='PROCESSING', verbose_name='Статус выполнения'),
        ),
    ]
