# Generated by Django 3.2.5 on 2021-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0013_auto_20210730_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='naloguser',
            name='added_to_registry',
            field=models.BooleanField(default=False, verbose_name='Пользователь добавлен в рееестр самозанятых Тинькофф'),
        ),
    ]
