# Generated by Django 3.2.5 on 2021-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0014_naloguser_added_to_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='naloguser',
            name='bank_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID банка из системы быстрых платежей'),
        ),
        migrations.AddField(
            model_name='naloguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='naloguser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='naloguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='naloguser',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
