# Generated by Django 3.2.5 on 2021-08-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0015_auto_20210810_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogbindpartnerrequestmodel',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='nalognotificationmodel',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='nalogrequestmodel',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='naloguser',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='nalogincomerequestmodel',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
    ]
