# Generated by Django 3.2.5 on 2021-09-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0017_alter_nalogrequestmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalogincomerequestmodel',
            name='canceled_reason',
            field=models.TextField(blank=True, choices=[('USER', 'Пользователь отменил чек из ЛК Мой налог'), ('REFUND', 'Возврат средств'), ('REGISTRATION_MISTAKE ', 'Чек сформирован ошибочно')], null=True, verbose_name='Причина аннулирования'),
        ),
        migrations.AlterField(
            model_name='nalogrequestmodel',
            name='name',
            field=models.TextField(choices=[('AuthRequest', 'Auth Request'), ('GetTaxpayerStatusRequest', 'Get Taxpayer Status Request'), ('GetNotificationsRequest', 'Get Notifications Request'), ('PostBindPartnerWithInnRequest', 'Post Bind Partner With Inn Request'), ('GetBindPartnerStatusRequest', 'Get Bind Partner Status Request'), ('PostIncomeRequestV2', 'Post Income Request V2'), ('PostCancelReceiptRequestV2', 'Post Cancel Receipt Request V2'), ('GetGrantedPermissionsRequest', 'Get Granted Permissions Request'), ('GetCancelIncomeReasonsListRequest', 'Get Cancel Income Reasons List Request'), ('PostPlatformRegistrationRequest', 'Post Platform Registration Request'), ('PostNotificationsAckRequest', 'Post Notifications Ack Request'), ('GetNewlyUnboundTaxpayersRequest', 'Get Newly Unbound Taxpayers Request'), ('GetIncomeRequestV2', 'Get Income Request V2')], verbose_name='Запрос'),
        ),
    ]
