# Generated by Django 3.2.5 on 2021-09-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0018_auto_20210906_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='NalogIncomeCancelReasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('code', models.CharField(max_length=255, verbose_name='Код отмены чека')),
                ('description', models.TextField(verbose_name='Описание причины отмены')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины отмены чеков',
                'db_table': 'appcraft_nalog_sdk_cancel_reasons',
            },
        ),
        migrations.RemoveField(
            model_name='nalogincomerequestmodel',
            name='canceled_reason',
        ),
    ]
