# Generated by Django 3.2.5 on 2021-09-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0019_auto_20210906_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogincomerequestmodel',
            name='canceled_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appcraft_nalog_sdk.nalogincomecancelreasonmodel', verbose_name='Причина аннулирования'),
        ),
    ]
