# Generated by Django 3.2.5 on 2021-09-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0020_nalogincomerequestmodel_canceled_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalogrequestmodel',
            name='name',
            field=models.TextField(choices=[('AuthRequest', 'Auth Request'), ('GetTaxpayerStatusRequest', 'Get Taxpayer Status Request'), ('GetNotificationsRequest', 'Get Notifications Request'), ('PostBindPartnerWithInnRequest', 'Post Bind Partner With Inn Request'), ('GetBindPartnerStatusRequest', 'Get Bind Partner Status Request'), ('PostIncomeRequestV2', 'Post Income Request V2'), ('PostCancelReceiptRequestV2', 'Post Cancel Receipt Request V2'), ('GetGrantedPermissionsRequest', 'Get Granted Permissions Request'), ('GetCancelIncomeReasonsListRequest', 'Get Cancel Income Reasons List Request'), ('PostPlatformRegistrationRequest', 'Post Platform Registration Request'), ('PostNotificationsAckRequest', 'Post Notifications Ack Request'), ('GetNewlyUnboundTaxpayersRequest', 'Get Newly Unbound Taxpayers Request'), ('GetIncomeRequestV2', 'Get Income Request V2'), ('GetPaymentDocumentsRequest', 'Get Payment Documents Request')], verbose_name='Запрос'),
        ),
        migrations.CreateModel(
            name='NalogDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('type', models.TextField(blank=True, null=True, verbose_name='Тип платежного документа')),
                ('index', models.TextField(blank=True, null=True, verbose_name='Индекс документа (УИН)')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='ФИО налогоплательщика')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес места жительства')),
                ('inn', models.TextField(blank=True, null=True, verbose_name='ИНН налогоплательщика')),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Сумма к оплате')),
                ('recipient_bank_name', models.TextField(blank=True, null=True, verbose_name='Банк получателя')),
                ('recipient_bank_bik', models.TextField(blank=True, null=True, verbose_name='БИК банка получателя')),
                ('recipient_bank_account_number', models.TextField(blank=True, null=True, verbose_name='Сумма к оплате')),
                ('recipient', models.TextField(blank=True, null=True, verbose_name='Получатель')),
                ('recipient_account_number', models.TextField(blank=True, null=True, verbose_name='Номер счёта получателя')),
                ('recipient_inn', models.TextField(blank=True, null=True, verbose_name='ИНН получателя')),
                ('recipient_kpp', models.TextField(blank=True, null=True, verbose_name='КПП получателя')),
                ('kbk', models.TextField(blank=True, null=True, verbose_name='Kbk')),
                ('oktmo', models.TextField(blank=True, null=True, verbose_name='Oktmo')),
                ('code_101', models.TextField(blank=True, null=True, verbose_name='Код для поля 101')),
                ('code_106', models.TextField(blank=True, null=True, verbose_name='Код для поля 106')),
                ('code_107', models.TextField(blank=True, null=True, verbose_name='Код для поля 107')),
                ('code_110', models.TextField(blank=True, null=True, verbose_name='Код для поля 110')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Оплатить до')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время создания документа')),
                ('source_id', models.TextField(blank=True, null=True, verbose_name='Внутренний идентификатор источника документа в ПП НПД')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcraft_nalog_sdk.naloguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Платежные документы',
                'db_table': 'appcraft_nalog_sdk_documents',
            },
        ),
    ]
