# Generated by Django 3.1.4 on 2021-09-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0022_auto_20210908_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalogrequestmodel',
            name='name',
            field=models.TextField(choices=[('AuthRequest', 'Auth Request'), ('GetTaxpayerStatusRequest', 'Get Taxpayer Status Request'), ('GetNotificationsRequest', 'Get Notifications Request'), ('PostBindPartnerWithInnRequest', 'Post Bind Partner With Inn Request'), ('GetBindPartnerStatusRequest', 'Get Bind Partner Status Request'), ('PostIncomeRequestV2', 'Post Income Request V2'), ('PostCancelReceiptRequestV2', 'Post Cancel Receipt Request V2'), ('GetGrantedPermissionsRequest', 'Get Granted Permissions Request'), ('GetCancelIncomeReasonsListRequest', 'Get Cancel Income Reasons List Request'), ('PostPlatformRegistrationRequest', 'Post Platform Registration Request'), ('PostNotificationsAckRequest', 'Post Notifications Ack Request'), ('GetNewlyUnboundTaxpayersRequest', 'Get Newly Unbound Taxpayers Request'), ('GetIncomeRequestV2', 'Get Income Request V2'), ('GetPaymentDocumentsRequest', 'Get Payment Documents Request'), ('GetKeysRequest', 'Get Keys Request')], verbose_name='Запрос'),
        ),
        migrations.CreateModel(
            name='NalogOfflineKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('sequence_number', models.IntegerField(verbose_name='Инкрементная часть чека')),
                ('base64_key', models.CharField(max_length=255, verbose_name='Ключ для формирования чека')),
                ('expire_time', models.DateTimeField(verbose_name='Срок валидности')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='appcraft_nalog_sdk.naloguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оффлайн ключ',
                'verbose_name_plural': 'Оффлайн ключи',
                'db_table': 'appcraft_nalog_offline_keys',
            },
        ),
    ]
