# Generated by Django 3.1.4 on 2021-09-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0023_auto_20210915_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogincomerequestmodel',
            name='receipt_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фискальный признак чека'),
        ),
    ]
