# Generated by Django 3.1.4 on 2021-09-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0024_nalogincomerequestmodel_receipt_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogincomerequestmodel',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='receipts', verbose_name='Изображение чека'),
        ),
    ]
