# Generated by Django 3.1.4 on 2021-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0025_nalogincomerequestmodel_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalogincomerequestmodel',
            name='cancel_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MessageID запроса на отмену дохода'),
        ),
    ]
