# Generated by Django 3.1.4 on 2021-09-07 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_ct_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_access', models.BooleanField(default=False, verbose_name='Имеет доступ')),
                ('object_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объект прав доступа',
                'verbose_name_plural': 'Объекты прав доступа',
                'db_table': 'app_admin__access_units',
            },
        ),
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('get', models.BooleanField(default=False, verbose_name='Получение')),
                ('add', models.BooleanField(default=False, verbose_name='Добавление')),
                ('edit', models.BooleanField(default=False, verbose_name='Редактирование')),
                ('delete', models.BooleanField(default=False, verbose_name='Удаление')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_admin.accessunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Право доступа пользователя',
                'verbose_name_plural': 'Права доступа пользователей',
                'db_table': 'app_admin__access_rights',
            },
        ),
    ]
