# Generated by Django 3.1.4 on 2021-09-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessright',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_right', to='app_admin.accessunit'),
        ),
    ]
