# Generated by Django 3.1.4 on 2021-09-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0072_auto_20210927_1531'),
        ('app_admin', '0002_auto_20210908_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
