# Generated by Django 3.1.4 on 2021-09-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_apikeytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeytoken',
            name='is_active',
        ),
    ]
