# Generated by Django 3.1.4 on 2021-07-16 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'app_games__goods_categories',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Исходное количество товара')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена в осколках')),
                ('grade', models.PositiveIntegerField(choices=[(1, 'DEFAULT'), (2, 'EPIC'), (3, 'LEGENDARY')], default=1, verbose_name='Уровень товара')),
                ('real_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Реальная цена')),
                ('real_price_currency', models.PositiveIntegerField(choices=[(0, 'BONUS'), (1, 'USD'), (2, 'EUR'), (3, 'RUB')], default=3, verbose_name='Валюта реальной цены')),
                ('categories', models.ManyToManyField(blank=True, db_table='app_games__prize_category', related_name='prizes', to='app_games.GoodsCategory')),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
                'db_table': 'app_games__prizes',
            },
        ),
        migrations.CreateModel(
            name='PrizeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номинал в осколках')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_games.prize')),
            ],
            options={
                'verbose_name': 'Призовая карточка',
                'verbose_name_plural': 'Призовые карточки',
                'db_table': 'app_games__prize_cards',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=3072, null=True)),
                ('bonus_value', models.PositiveIntegerField(default=1, verbose_name='Баллов за выполнение')),
                ('period', models.PositiveIntegerField(choices=[(1, 'DAILY'), (2, 'WEEKLY'), (3, 'SUPER')], default=1, verbose_name='Период задачи')),
                ('type', models.PositiveIntegerField(choices=[(1, 'COMMON'), (2, 'PROMOTION')], default=1, verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'app_games__tasks',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_games.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание пользователя',
                'verbose_name_plural': 'Задания пользователей',
                'db_table': 'app_games__task_user',
            },
        ),
        migrations.CreateModel(
            name='UserPrizeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Накоплено осколков на приз')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата полного накопления')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_games.prize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс пользователя по призу',
                'verbose_name_plural': 'Прогресс пользователей по призам',
                'db_table': 'app_games__user_prize_progress',
            },
        ),
        migrations.CreateModel(
            name='UserFavouritePrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_games.prize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приоритетный приз пользователя',
                'verbose_name_plural': 'Приоритетные призы пользователей',
                'db_table': 'app_games__user_favourite_prizes',
            },
        ),
        migrations.CreateModel(
            name='PrizeCardsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('bonuses_acquired', models.PositiveIntegerField(default=0, verbose_name='Получено всего бонусов на момент выдачи')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_games.prizecard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История выдачи призовой карточки',
                'verbose_name_plural': 'История выдачи призовых карточек',
                'db_table': 'app_games__prize_cards_history',
            },
        ),
    ]
