# Generated by Django 3.1.4 on 2021-08-02 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizecardshistory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_history', to='app_games.prizecard'),
        ),
        migrations.AlterField(
            model_name='prizecardshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
