# Generated by Django 3.1.4 on 2021-08-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0002_auto_20210802_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizecardshistory',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия карточки'),
        ),
    ]
