# Generated by Django 3.1.4 on 2021-08-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0003_prizecardshistory_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actions_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество действий для выполнения задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'OPEN_APP'), (2, 'COMPLETE_SHIFT')], null=True, verbose_name='Вид задачи'),
        ),
    ]
