# Generated by Django 3.1.4 on 2021-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0004_auto_20210817_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actions_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Дополнительное значение для действий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'OPEN_APP'), (2, 'COMPLETE_SHIFT_WITH_MIN_RATING')], null=True, verbose_name='Вид задачи'),
        ),
    ]
