# Generated by Django 3.1.4 on 2020-12-16 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('owner_content_type_id', models.IntegerField(blank=True, null=True)),
                ('owner_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/media')),
                ('preview', models.FileField(blank=True, null=True, upload_to='files/media')),
                ('format', models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'DOCUMENT'), (2, 'IMAGE'), (3, 'VIDEO'), (4, 'AUDIO')], null=True, verbose_name='Тип файла')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'OTHER'), (1, 'AVATAR'), (2, 'PASSPORT'), (3, 'INN'), (4, 'SNILS'), (5, 'MEDICAL_BOOK'), (6, 'DRIVER_LICENCE'), (7, 'LOGO')], null=True, verbose_name='Принадлежность')),
                ('width', models.IntegerField(blank=True, default=None, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.BigIntegerField(blank=True, default=None, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'db_table': 'app_media',
            },
        ),
    ]
