# Generated by Django 3.1.4 on 2020-12-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='preview'),
        ),
    ]
