# Generated by Django 3.1.4 on 2021-01-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0003_auto_20201225_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediamodel',
            old_name='owner_content_type',
            new_name='_owner_content_type',
        ),
        migrations.RenameField(
            model_name='mediamodel',
            old_name='owner_content_type_id',
            new_name='_owner_content_type_id',
        ),
        migrations.RenameField(
            model_name='mediamodel',
            old_name='owner_id',
            new_name='_owner_id',
        ),
    ]
