# Generated by Django 3.1.4 on 2021-01-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0005_auto_20210114_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediamodel',
            name='_owner_content_type',
        ),
        migrations.RemoveField(
            model_name='mediamodel',
            name='_owner_content_type_id',
        ),
        migrations.RemoveField(
            model_name='mediamodel',
            name='_owner_id',
        ),
    ]
