# Generated by Django 3.1.4 on 2021-03-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0009_auto_20210315_1417'),
        ('app_media', '0009_auto_20210315_0933'),
    ]

    operations = [
    ]
