# Generated by Django 3.1.4 on 2020-12-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
