# Generated by Django 3.1.4 on 2020-12-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0002_auto_20201221_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
