# Generated by Django 3.1.4 on 2020-12-29 08:52

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0004_auto_20201228_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='names',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
