# Generated by Django 3.1.4 on 2021-01-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0005_language_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='native',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='native',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='native',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='native',
        ),
    ]
