# Generated by Django 3.1.4 on 2021-02-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0008_triggers_for_tsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
