# Generated by Django 3.1.4 on 2021-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='command_data',
            field=models.JSONField(default=dict),
        ),
    ]
