# Generated by Django 3.1.4 on 2021-04-06 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_chats', '0004_auto_20210405_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='app_chats.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Состояние сообщения для пользователя',
                'verbose_name_plural': 'Состояния сообщений для пользователей',
                'db_table': 'app_chats__message_stat',
            },
        ),
    ]
