# Generated by Django 3.1.4 on 2021-04-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0007_auto_20210407_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestat',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='app_chats.message'),
        ),
    ]
