# Generated by Django 3.1.4 on 2021-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0009_auto_20210412_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='bot_state',
            field=models.IntegerField(choices=[(0, 'IDLE'), (1, 'QUESTION_ASKED'), (2, 'IRRELEVANT_ANSWER_TO_QUESTION')], default=0, verbose_name='Состояние бота'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='is_bot_enabled',
            field=models.BooleanField(default=True, verbose_name='Бот для чата включен'),
        ),
    ]
