# Generated by Django 3.1.4 on 2021-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0010_auto_20210416_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='command_data',
        ),
        migrations.RemoveField(
            model_name='message',
            name='form_status',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.PositiveIntegerField(choices=[(1, 'SIMPLE'), (2, 'INFO')], default=1),
        ),
    ]
