# Generated by Django 3.1.4 on 2021-04-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_chats', '0011_auto_20210422_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruled_chats', to=settings.AUTH_USER_MODEL, verbose_name='Активный менеджер'),
        ),
        migrations.AddField(
            model_name='chat',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'BOT_IS_USED'), (1, 'NEED_MANAGER'), (2, 'MANAGER_CONNECTED')], default=0, verbose_name='Участие менеджера в чате'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='bot_state',
            field=models.IntegerField(choices=[(0, 'IDLE'), (1, 'QUESTION_ASKED'), (2, 'IRRELEVANT_ANSWER_TO_QUESTION')], default=0, verbose_name='Состояние бота для СМЗ'),
        ),
    ]
