# Generated by Django 3.1.4 on 2021-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0012_auto_20210427_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='icon_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'DEFAULT'), (1, 'ALARM'), (2, 'CONGRATULATIONS'), (3, 'WAITING')], null=True),
        ),
    ]
