# Generated by Django 3.1.4 on 2021-05-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0013_message_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='icon_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'DEFAULT'), (1, 'ALARM'), (2, 'CONGRATULATIONS'), (3, 'WAITING'), (4, 'SUPPORT')], null=True),
        ),
    ]
