# Generated by Django 3.1.4 on 2021-05-11 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_chats', '0014_auto_20210511_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active_managers',
            field=models.ManyToManyField(db_table='app_chats__active_managers', related_name='ruled_chats', to=settings.AUTH_USER_MODEL, verbose_name='Активные менеджеры'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='active_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruled_chat', to=settings.AUTH_USER_MODEL, verbose_name='Активный менеджер'),
        ),
    ]
