# Generated by Django 3.1.4 on 2021-05-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0015_auto_20210511_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='active_manager',
        ),
    ]
