# Generated by Django 3.1.4 on 2021-05-13 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0016_remove_chat_active_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
