# Generated by Django 3.1.4 on 2021-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0018_message_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='json',
        ),
        migrations.AddField(
            model_name='message',
            name='buttons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
