version: '3.5'

networks:
  giberno_stage:

services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - giberno_stage
  db:
    image: shmeser/postgis-plpython3:latest
    restart: always
    networks:
      - giberno_stage
    ports:
      - "${ST_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${ST_POSTGRES_DB}
      POSTGRES_USER: ${ST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ST_POSTGRES_PASSWORD}
    volumes:
      - ./data/postgisdb:/var/lib/postgresql/data
  api:
    image: registry.appcraft.team:5005/giberno/giberno-server:stage
    restart: always
    command: bash -c "python3 manage.py migrate && python3 manage.py seed && python3 manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p ${ST_API_PORT} giberno.asgi:application"
    environment:
      REDIS_HOST: redis
      CELERY_BROKER: redis://redis:6379/0
      HOST_DOMAIN: ${ST_HOST_DOMAIN}
      HOST_IP: ${ST_HOST_IP}
      DB_HOST: db
      DB_NAME: ${ST_POSTGRES_DB}
      DB_USER: ${ST_POSTGRES_USER}
      DB_PASSWORD: ${ST_POSTGRES_PASSWORD}
      SUPERUSER_PASS: ${ST_SUPERUSER_PASS}
      ENVIRONMENT: ${ST_ENVIRONMENT}
      TELEGRAM_BOT_TOKEN: ${ST_TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_PASSWORD: ${TELEGRAM_BOT_PASSWORD}
      FCM_SERVER_KEY: ${FCM_SERVER_KEY}
      GOOGLE_CLOUD_API_KEY: ${GOOGLE_CLOUD_API_KEY}
      SECRET_KEY: ${ST_SECRET_KEY}
      VK_APP_ID: ${DEV_VK_APP_ID}
      VK_APP_SECRET: ${DEV_VK_APP_SECRET}
      API_PORT: ${ST_API_PORT}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      DEBUG: ${DEBUG}
    ports:
      - "127.0.0.1:${ST_API_PORT}:${ST_API_PORT}"
    networks:
      - giberno_stage
    depends_on:
      - db
      - redis
    volumes:
      - ./files:/code/files
  celery:
    image: registry.appcraft.team:5005/giberno/giberno-server:stage
    command: celery -A giberno worker -l info
    environment:
      REDIS_HOST: redis
      CELERY_BROKER: redis://redis:6379/0
      DB_HOST: db
      DB_NAME: ${ST_POSTGRES_DB}
      DB_USER: ${ST_POSTGRES_USER}
      DB_PASSWORD: ${ST_POSTGRES_PASSWORD}
      SUPERUSER_PASS: ${ST_SUPERUSER_PASS}
      ENVIRONMENT: ${ST_ENVIRONMENT}
      FCM_SERVER_KEY: ${FCM_SERVER_KEY}
      GOOGLE_CLOUD_API_KEY: ${GOOGLE_CLOUD_API_KEY}
      SECRET_KEY: ${ST_SECRET_KEY}
    depends_on:
      - db
      - redis
    networks:
      - giberno_stage
    volumes:
      - ./files:/code/files
  celery-beat:
    image: registry.appcraft.team:5005/giberno/giberno-server:stage
    command: celery -A giberno beat -l info
    environment:
      REDIS_HOST: redis
      CELERY_BROKER: redis://redis:6379/0
      DB_HOST: db
      DB_NAME: ${ST_POSTGRES_DB}
      DB_USER: ${ST_POSTGRES_USER}
      DB_PASSWORD: ${ST_POSTGRES_PASSWORD}
      SUPERUSER_PASS: ${ST_SUPERUSER_PASS}
      ENVIRONMENT: ${ST_ENVIRONMENT}
      FCM_SERVER_KEY: ${FCM_SERVER_KEY}
      GOOGLE_CLOUD_API_KEY: ${GOOGLE_CLOUD_API_KEY}
      SECRET_KEY: ${ST_SECRET_KEY}
    depends_on:
      - db
      - redis
    networks:
      - giberno_stage
    volumes:
      - ./files:/code/files