# Generated by Django 3.1.4 on 2020-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmodel',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmodel',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmodel',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
