# Generated by Django 3.1.4 on 2020-12-08 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reg_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Приглашение на регистрацию от'),
        ),
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('social_id', models.CharField(max_length=255, null=True)),
                ('access_token', models.CharField(max_length=2048, null=True)),
                ('access_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Способ авторизации пользователя',
                'verbose_name_plural': 'Способы авторизаций пользователей',
                'db_table': 'app_users__socials',
            },
        ),
        migrations.CreateModel(
            name='JwtToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=128, null=True)),
                ('platform_name', models.CharField(blank=True, max_length=128, null=True)),
                ('vendor', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JWT токен',
                'verbose_name_plural': 'JWT токены',
                'db_table': 'app_users__jwt_tokens',
            },
        ),
    ]
