# Generated by Django 3.1.4 on 2020-12-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20201210_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmodel',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
