# Generated by Django 3.1.4 on 2020-12-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_remove_userprofile_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Профиль редактировался после регистрации'),
        ),
    ]
