# Generated by Django 3.1.4 on 2020-12-21 07:32

import app_users.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0001_initial'),
        ('app_users', '0005_remove_userprofile_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_geo.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Гражданство пользователя',
                'verbose_name_plural': 'Гражданство пользователей',
                'db_table': 'app_users__profile_nationality',
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('proficiency', models.PositiveIntegerField(choices=[(0, 'BEGINNER'), (1, 'ELEMENTARY'), (2, 'INTERMEDIATE'), (3, 'UPPER_INTERMEDIATE'), (4, 'ADVANCED'), (5, 'PROFICIENCY')], default=app_users.enums.LanguageProficiency['BEGINNER'], verbose_name='Уровень владения языком')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_geo.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Язык пользователя',
                'verbose_name_plural': 'Языки пользователей',
                'db_table': 'app_users__profile_language',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, through='app_users.UserLanguage', to='app_geo.Language'),
        ),
    ]
