# Generated by Django 3.1.4 on 2020-12-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0003_country_iso_code'),
        ('app_users', '0006_auto_20201221_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nationalities',
            field=models.ManyToManyField(blank=True, through='app_users.UserNationality', to='app_geo.Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
