# Generated by Django 3.1.4 on 2020-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_auto_20201225_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmodel',
            name='is_for_reg',
            field=models.BooleanField(default=False, verbose_name='Использовался для регистрации'),
        ),
    ]
