# Generated by Django 3.1.4 on 2021-01-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0006_auto_20210111_1352'),
        ('app_users', '0009_userprofile_show_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bonus_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки славы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_geo.city'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_vacancies_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество избранных вакансий'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Правила использования приняты'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Профиль проверен'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agreement_accepted',
            field=models.BooleanField(default=False, verbose_name='Пользовательское соглашение принято'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationalities',
            field=models.ManyToManyField(blank=True, related_name='nationalities', through='app_users.UserNationality', to='app_geo.Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Политика конфиденциальности принята'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reg_reference_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
    ]
