# Generated by Django 3.1.4 on 2021-01-13 09:56

import app_users.enums
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_auto_20210113_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('enabled_types', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'SYSTEM')]), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений пользователя',
                'verbose_name_plural': 'Настройки уведомлений пользователей',
                'db_table': 'app_users__notifications_settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject_id', models.IntegerField(blank=True, null=True, verbose_name='ID сущности в уведомлении')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сообщение')),
                ('type', models.IntegerField(choices=[(0, 'SYSTEM')], default=app_users.enums.NotificationType['SYSTEM'], verbose_name='Тип отправителя уведомления')),
                ('action', models.IntegerField(choices=[(0, 'APP'), (1, 'VACANCY')], default=app_users.enums.NotificationAction['APP'], verbose_name='Открываемый экран')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('push_tokens_android', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None)),
                ('firebase_response_android', models.JSONField(blank=True, null=True)),
                ('push_tokens_ios', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None)),
                ('firebase_response_ios', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в Firebase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'app_users__notifications',
            },
        ),
        migrations.RunSQL(
            '''
                INSERT INTO app_users__notifications_settings ("created_at", "updated_at", "deleted", "enabled_types", "user_id")
                SELECT NOW() AS "created_at", NOW() AS "updated_at", FALSE AS "deleted", ARRAY[0] AS "enabled_types", id AS "user_id"
                FROM app_users__profiles
                ORDER BY "user_id";
            '''
        )
    ]
