# Generated by Django 3.1.4 on 2021-01-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_usercareer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на профиль в Facebook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на профиль в Intsagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на профиль в ВКонтанте'),
        ),
    ]
