# Generated by Django 3.1.4 on 2021-01-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_auto_20210118_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'SCHOOL'), (1, 'COLLEGE'), (2, 'UNIVERSITY')], null=True, verbose_name='Образование'),
        ),
    ]
