# Generated by Django 3.1.4 on 2021-01-19 08:49

import app_users.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_userprofile_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'OTHER'), (1, 'PASSPORT'), (2, 'INN'), (3, 'SNILS'), (4, 'MEDICAL_BOOK'), (5, 'DRIVER_LICENCE')], default=app_users.enums.DocumentType['OTHER'])),
                ('series', models.CharField(blank=True, max_length=128, null=True, verbose_name='Серия')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер')),
                ('category', models.CharField(blank=True, max_length=128, null=True, verbose_name='Категория')),
                ('department_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код подразделения')),
                ('issue_place', models.CharField(blank=True, max_length=128, null=True, verbose_name='Место выдачи')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'app_users__documents',
            },
        ),
    ]
