# Generated by Django 3.1.4 on 2021-01-22 04:53

import app_users.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon_type',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'REQUEST_APPROVED'), (2, 'REQUEST_DECLINED'), (3, 'MONEY_RECEIVED'), (4, 'REWARD_RECEIVED'), (5, 'DOCS_APPROVED'), (6, 'DOCS_DECLINED'), (7, 'SHIFT_AVAILABLE'), (8, 'SHIFT_START_SOON'), (9, 'LEAVED_SHOP_AREA'), (10, 'VACANCY_APPROVED'), (11, 'VACANCY_DECLINED'), (12, 'WORKER_CANCELED_VACANCY'), (13, 'SECURITY_CALL'), (14, 'SECURITY_CANCELLATION_REASON')], default=app_users.enums.NotificationIcon['DEFAULT'], verbose_name='Тип иконки'),
        ),
    ]
