# Generated by Django 3.1.4 on 2021-02-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_userprofile_distributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='firebase_response_android',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='firebase_response_ios',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
    ]
