# Generated by Django 3.1.4 on 2021-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0021_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
