# Generated by Django 3.1.4 on 2021-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0018_auto_20210224_0902'),
        ('app_users', '0023_userprofile_manager_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager_shops',
            field=models.ManyToManyField(blank=True, related_name='manager_shops', to='app_market.Shop', verbose_name='Торговая сеть'),
        ),
    ]
