# Generated by Django 3.1.4 on 2021-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0020_vacancy_places_count'),
        ('app_users', '0024_userprofile_manager_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manager_shops',
            field=models.ManyToManyField(blank=True, related_name='manager_shops', to='app_market.Shop', verbose_name='Магазины'),
        ),
    ]
