# Generated by Django 3.1.4 on 2021-03-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0022_auto_20210319_1428'),
        ('app_users', '0026_auto_20210318_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='manager_position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manager_shops',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='shops', to='app_market.Shop', verbose_name='Магазины'),
        ),
    ]
