# Generated by Django 3.1.4 on 2021-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0027_auto_20210322_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationssettings',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
