# Generated by Django 3.1.4 on 2021-03-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0028_notificationssettings_sound_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sound_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Уведомление со звуком'),
        ),
    ]
