# Generated by Django 3.1.4 on 2021-04-02 13:42

import app_users.enums
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0029_notification_sound_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.IntegerField(choices=[(0, 'APP'), (1, 'VACANCY'), (2, 'SHIFT'), (3, 'SHOP'), (4, 'DISTRIBUTOR'), (5, 'USER'), (6, 'CHAT')], default=app_users.enums.NotificationAction['APP'], verbose_name='Открываемый экран'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'SYSTEM'), (1, 'CHAT')], default=app_users.enums.NotificationType['SYSTEM'], verbose_name='Тип отправителя уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationssettings',
            name='enabled_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'SYSTEM'), (1, 'CHAT')]), blank=True, null=True, size=None),
        ),
    ]
