# Generated by Django 3.1.4 on 2021-04-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0026_auto_20210423_1116'),
        ('app_users', '0030_auto_20210402_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='distributors',
            field=models.ManyToManyField(blank=True, related_name='staff', to='app_market.Distributor', verbose_name='Торговая сеть'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='staff', to='app_market.Shop', verbose_name='Магазины'),
        ),
    ]
