# Generated by Django 3.1.4 on 2021-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0033_auto_20210602_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rates_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в общем рейтинге'),
        ),
    ]
