# Generated by Django 3.1.4 on 2021-07-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0035_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
        migrations.AddField(
            model_name='card',
            name='hash',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='pan',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Маскированный номер карты'),
        ),
        migrations.AddField(
            model_name='card',
            name='salt',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='valid_through',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Действительна до'),
        ),
    ]
