# Generated by Django 3.1.4 on 2021-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0036_auto_20210709_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='card',
            name='salt',
            field=models.CharField(max_length=128),
        ),
    ]
