# Generated by Django 3.1.4 on 2021-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0040_usermoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Общий рейтинг'),
        ),
    ]
