# Generated by Django 3.1.4 on 2021-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0042_auto_20210713_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bonus_balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bonuses_acquired',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего получено очков славы'),
        ),
    ]
