# Generated by Django 3.1.4 on 2021-08-02 11:15

import app_users.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0043_auto_20210716_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'OTHER'), (1, 'PASSPORT'), (2, 'INN'), (3, 'SNILS'), (4, 'MEDICAL_BOOK'), (5, 'DRIVER_LICENCE'), (6, 'VACCINATION_CERTIFICATE'), (7, 'VISA'), (8, 'RESIDENT_CARD'), (9, 'MIGRATION_CARD')], default=app_users.enums.DocumentType['OTHER']),
        ),
    ]
