# Generated by Django 3.1.4 on 2021-09-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0022_auto_20210908_0847'),
        ('app_users', '0046_userprofile_nalog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nalog_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcraft_nalog_sdk.naloguser'),
        ),
    ]
