# Generated by Django 3.1.4 on 2021-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0047_userprofile_nalog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='identifier',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Идентификатор'),
        ),
    ]
