# Generated by Django 3.1.4 on 2021-09-09 12:28

import app_users.enums
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_nalog_sdk', '0022_auto_20210908_0847'),
        ('app_users', '0048_document_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='nalog_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcraft_nalog_sdk.nalognotificationmodel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'SYSTEM'), (1, 'CHAT'), (2, 'NALOG')], default=app_users.enums.NotificationType['SYSTEM'], verbose_name='Тип отправителя уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationssettings',
            name='enabled_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'SYSTEM'), (1, 'CHAT'), (2, 'NALOG')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nalog_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='appcraft_nalog_sdk.naloguser'),
        ),
    ]
