# Generated by Django 3.1.4 on 2021-09-15 08:50

import app_users.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0050_auto_20210909_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'OTHER'), (1, 'PASSPORT'), (2, 'INN'), (3, 'SNILS'), (4, 'MEDICAL_BOOK'), (5, 'DRIVER_LICENCE'), (6, 'VACCINATION_CERTIFICATE'), (7, 'VISA'), (8, 'RESIDENT_CARD'), (9, 'MIGRATION_CARD'), (10, 'DIPLOMA'), (11, 'CERTIFICATE'), (12, 'CARD'), (13, 'BILL')], default=app_users.enums.DocumentType['OTHER']),
        ),
    ]
