# Generated by Django 3.1.4 on 2021-03-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0021_auto_20210317_2220'),
        ('app_feedback', '0002_review_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.shift'),
        ),
    ]
