# Generated by Django 3.1.4 on 2020-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchat',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
    ]
