# Generated by Django 3.1.4 on 2020-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0002_auto_20201229_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
