# Generated by Django 3.1.4 on 2020-12-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0003_botmessage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='chat_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
