# Generated by Django 3.1.4 on 2021-04-14 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0004_botmessage_chat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('code', models.IntegerField(blank=True, choices=[(0, 'DISABLE'), (1, 'GREETING'), (2, 'FAREWELL'), (3, 'VACANCY')], null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Тема разговора для бота',
                'verbose_name_plural': 'Темы разговоров для бота',
                'db_table': 'app_bot__intents',
            },
            managers=[
                ('support', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IntentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=255)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='app_bot.intent')),
            ],
            options={
                'verbose_name': 'Вариант ответа для теме',
                'verbose_name_plural': 'Варианты ответов для теме',
                'db_table': 'app_bot__intents_responses',
            },
        ),
        migrations.CreateModel(
            name='IntentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=255)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app_bot.intent')),
            ],
            options={
                'verbose_name': 'Вариант запроса для темы',
                'verbose_name_plural': 'Варианты запросов для темы',
                'db_table': 'app_bot__intents_requests',
            },
        ),
    ]
