# Generated by Django 3.1.4 on 2021-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0005_intent_intentrequest_intentresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentresponse',
            options={'verbose_name': 'Вариант ответа для темы', 'verbose_name_plural': 'Варианты ответов для темы'},
        ),
        migrations.AlterField(
            model_name='intent',
            name='code',
            field=models.IntegerField(blank=True, choices=[(0, 'DISABLE'), (1, 'GREETING'), (2, 'FAREWELL'), (3, 'ANSWERS_POSITIVE'), (4, 'ANSWERS_NEGATIVE'), (5, 'COMPLY')], null=True),
        ),
    ]
