# Generated by Django 3.1.4 on 2021-05-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0006_auto_20210416_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='code',
            field=models.IntegerField(blank=True, choices=[(0, 'DISABLE'), (1, 'GREETING'), (2, 'FAREWELL'), (3, 'ANSWERS_POSITIVE'), (4, 'ANSWERS_NEGATIVE'), (5, 'COMPLY'), (6, 'SHOP_ADDRESS'), (7, 'VACANCY_REQUIREMENTS'), (8, 'APPEAL_CONFIRMATION'), (9, 'SHIFT_TIME'), (10, 'WHAT_TO_TAKE_WITH'), (11, 'CANCEL_APPEAL'), (12, 'VACANCIES_VARIETY'), (13, 'VACANCY_RATES')], null=True),
        ),
    ]
