# Generated by Django 3.1.4 on 2021-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0007_auto_20210518_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='code',
            field=models.IntegerField(blank=True, choices=[(0, 'DISABLE'), (1, 'GREETING'), (2, 'HOW_ARE_YOU'), (3, 'VACANCY_DETAILS'), (4, 'HOW_TO_EMPLOY'), (5, 'COMPLY'), (6, 'SHOP_ADDRESS'), (7, 'VACANCY_REQUIREMENTS'), (8, 'APPEAL_CONFIRMATION'), (9, 'SHIFT_TIME'), (10, 'WHAT_TO_TAKE_WITH'), (11, 'CANCEL_APPEAL'), (12, 'VACANCIES_VARIETY'), (13, 'VACANCY_RATES'), (14, 'WHAT_YOU_CAN'), (15, 'OBSCENE_LANGUAGE')], null=True),
        ),
    ]
